exclude: |
  (?x)^(
    region-tests/
    | fixity-tests/
    | data/examples/
    | data/fourmolu/
    | data/diff-tests/
    | data/parse-failures/
  )

repos:
  - repo: local
    hooks:
      - id: fourmolu
        name: fourmolu
        entry: scripts/run-fourmolu.sh --mode=inplace
        language: system
        files: '\.(hs|hs-boot)$'

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: check-symlinks
      - id: end-of-file-fixer
      # do not turn these on, to prevent merge conflicts when
      # merging upstream ormolu changes
      # - id: trailing-whitespace
